# Generated by Django 3.2.8 on 2021-10-31 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.neighbourhood'),
        ),
    ]
