# Generated by Django 3.2.8 on 2021-10-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='banner.jpg', upload_to='hood/'),
        ),
    ]
