# Generated by Django 3.2.8 on 2021-10-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='banner.png', upload_to='hood/'),
        ),
    ]
